# Generated by Django 5.2.7 on 2025-10-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdJourney', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningentry',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
